services:
  mysql:
    image: mysql:8.0
    container_name: go-lobby-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: go_lobby
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: go-lobby-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: go-lobby-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  api:
    build: .
    container_name: go-lobby-api
    command: ["/app/api"]
    ports:
      - "8080:8080"
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
    depends_on:
      - mysql
      - redis
      - rabbitmq
  worker:
    build: .
    container_name: go-lobby-worker
    command: ["/app/worker"]
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
    depends_on:
      - mysql
      - redis
      - rabbitmq


volumes:
  mysql_data:

